### ISSUE TITLE
fit_transform fails with label of -1 (or any negative value)

### ISSUE THREAD

**Issue by nmetts** [stavskal/ADASYN#2]
The fit_transform function calls oversample. The oversample function uses the numpy.bincount function, which cannot handle negative integers: http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.bincount.html

**Comment by stavskal** [comment]
I will look into that as soon as possible. Thanks for the feedback!

**Comment by stavskal** [comment]
Should be fine now, check and let me know!

**Comment by nmetts** [comment]
I can confirm that it now works with labels with a negative value. Thanks!

**Comment by stavskal** [comment]
Glad to hear the problem is solved!
